### ISSUE TITLE
CMake-generated paths are absolute

### ISSUE THREAD

**Issue by ThreeFx** [seL4/camkes-vm-examples-manifest#5]
No idea whether this is a problem, but here goes:

* I checked out #4 and synced everything using `repo`
* On my host machine I ran `../init-build.sh`
* I called `ninja` in my dev environment, which is the official camkes docker image

Ninja invokes CMake (why?) and it now complains about paths not existing, due to absolute paths being used internally.

This is not the case for all manifests, e.g. `seL4test-manifest` works just fine using my method.

There are three possible solutions I see to this:

* Do nothing, and just tell everyone to run the steps from the same machine
* Make CMake use relative paths (my preferred solution, hence why I reported it here)
* Bindmount the `/host` folder under `$PWD` as well in the docker image (hacky but should work :tm:)

**Comment by kent-mcleod** [comment]
It's generally expected that `../init-build.sh` is called from the docker container.  It invokes CMake for the first time and CMake detects which toolchains and flags to use from the host environment which needs to be the same as the environment that Ninja is called from.  
What reasons do you have for needing to run `../init-build.sh` from outside of the docker?

**Comment by kent-mcleod** [comment]
Do you have an output of which parts of the build script CMake is complaining about?  It could be something easy to change to use relative paths anyway.  I expect that any part of the build that references `CMAKE_SOURCE_DIR` or `CMAKE_BINARY_DIR` will use an absolute path and not work across different directory mounts.

**Comment by ThreeFx** [comment]
> It's generally expected that ../init-build.sh is called from the docker container.

Ah in that case I'd say that this is a user error :) It does make sense to run them from the same environment, for me it was simply a matter of convenience since my shell completion has the `../init-build.sh` invocation saved.

We can probably close this issue in that case.
